language: node_js
node_js:
  - '14'

before_install:
  - sudo apt-get install moreutils
  - npm install -g yarn

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

install:
  - yarn cache clean
  - sh scripts/sh/install.sh
  - yarn run bootstrap
  - yarn run build

script:
  - yarn test:report

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx -p @qiwi/semrel-toolkit multi-semrel
